#!/usr/bin/env python3
"""Cache PokeAPI data and pinned pixel sprites; generate a small LVGL atlas.

Run using a Python environment with Pillow. Downloads are development inputs;
the pet runs entirely from local bundled assets at runtime.
"""
import hashlib
import io
import json
from pathlib import Path
import time
import urllib.request

from PIL import Image, ImageSequence

ROOT = Path(__file__).resolve().parents[1]
SPRITES_COMMIT = "a3a1432e688ea028f12c51371d5253037cb9f17b"
# PokeAPI's own static mirror is used when its public HTTP service is unavailable.
DATA_COMMIT = "02a8d9dd1b1a4e102b8b32d786d17017e8c9769a"
FAMILIES = [("charmander", 4), ("pikachu", 172), ("bulbasaur", 1),
            ("squirtle", 7), ("dratini", 147), ("gastly", 92)]
CACHE = ROOT / ".local/pokeapi"
OUT = ROOT / "assets/pokemon"


def download(url, path):
    if path.exists():
        return path.read_bytes()
    error = None
    for attempt in range(3):
        try:
            request = urllib.request.Request(url, headers={"User-Agent": "TokenPet/0.1 (local cached personal project)"})
            with urllib.request.urlopen(request, timeout=30) as response:
                body = response.read(20 * 1024 * 1024)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(body)
            return body
        except Exception as exc:
            error = exc
            if attempt < 2:
                time.sleep(attempt + 1)
    raise error


def api(resource, ident):
    # This official JSON mirror contains the same schema as pokeapi.co.
    url = f"https://raw.githubusercontent.com/PokeAPI/api-data/{DATA_COMMIT}/data/api/v2/{resource}/{ident}/index.json"
    return json.loads(download(url, CACHE / resource / f"{ident}.json"))


def localized(species):
    return next((row["name"] for row in species["names"] if row["language"]["name"].lower() == "zh-hans"), species["name"])


def flatten(node):
    result = [node["species"]]
    for child in node["evolves_to"]:
        result.extend(flatten(child))
    return result


def atlas(pokemon):
    target = ROOT / "firmware/main/pet_assets.c"
    parts = ['/* Generated by pets/scripts/fetch_pokemon.py. Source: PokeAPI/sprites. */', '#include "pet_assets.h"']
    descriptors = []
    for item in pokemon:
        ident = item["id"]
        image = Image.open(OUT / f"{ident}.gif")
        frames = [f.convert("RGBA") for f in ImageSequence.Iterator(image)]
        bounds = [frame.getchannel('A').getbbox() for frame in frames]
        bounds = [b for b in bounds if b]
        bbox = (min(b[0] for b in bounds), min(b[1] for b in bounds),
                max(b[2] for b in bounds), max(b[3] for b in bounds))
        ratio = min(112 / (bbox[2] - bbox[0]), 112 / (bbox[3] - bbox[1]))
        size = (max(1, round((bbox[2] - bbox[0]) * ratio)), max(1, round((bbox[3] - bbox[1]) * ratio)))
        # Four distinct timeline samples per species; all occupy Flash, not heap.
        samples = [frames[(i * len(frames)) // 4] for i in range(4)]
        for frame_index, frame in enumerate(samples):
            canvas = Image.new("RGBA", (120, 120))
            frame = frame.crop(bbox).resize(size, Image.Resampling.NEAREST)
            canvas.alpha_composite(frame, ((120 - frame.width) // 2, (120 - frame.height) // 2))
            raw = canvas.tobytes("raw", "BGRA")
            symbol = f"pet_{ident}_{frame_index}"
            lines = [','.join(str(b) for b in raw[i:i+32]) for i in range(0, len(raw), 32)]
            parts.append(f"static const uint8_t {symbol}_data[] = {{\n" + ',\n'.join(lines) + "\n};")
            parts.append(f"static const lv_image_dsc_t {symbol} = {{.header = {{.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_ARGB8888, .w = 120, .h = 120, .stride = 480}}, .data_size = sizeof({symbol}_data), .data = {symbol}_data}};")
        descriptors.append(f'{{{ident}, "{item["name"]}", "{item["name_zh"]}", {{&pet_{ident}_0, &pet_{ident}_1, &pet_{ident}_2, &pet_{ident}_3}}}}')
    parts.append("const pet_sprite_t pet_sprites[] = {" + ',\n'.join(descriptors) + "};")
    parts.append("const unsigned pet_sprite_count = sizeof(pet_sprites) / sizeof(pet_sprites[0]);")
    target.write_text('\n\n'.join(parts) + '\n')
    target.with_suffix('.h').write_text('''#pragma once
#include "lvgl.h"
typedef struct { unsigned id; const char *name; const char *name_zh; const lv_image_dsc_t *frames[4]; } pet_sprite_t;
extern const pet_sprite_t pet_sprites[];
extern const unsigned pet_sprite_count;
''')
    family_lines = []
    for _, base in FAMILIES:
        species = api("pokemon-species", base)
        chain_id = species["evolution_chain"]["url"].strip('/').split('/')[-1]
        ids = [int(row["url"].strip('/').split('/')[-1]) for row in flatten(api('evolution-chain', chain_id)['chain'])]
        if len(ids) != 3:
            raise ValueError(f"Expected a real three-stage evolution chain: {base}")
        family_lines.append('{' + ','.join(map(str, ids)) + '}')
    (ROOT / 'firmware/main/pet_families.h').write_text('#pragma once\n#define PET_FAMILY_COUNT 6\nstatic const unsigned pet_family_species[PET_FAMILY_COUNT][3] = {' + ','.join(family_lines) + '};\n')


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    families = []
    species_by_id = {}
    for name, base in FAMILIES:
        species = api("pokemon-species", base)
        chain_id = species["evolution_chain"]["url"].strip('/').split('/')[-1]
        chain = api("evolution-chain", chain_id)
        ids = [int(row["url"].strip('/').split('/')[-1]) for row in flatten(chain['chain'])]
        for ident in ids:
            species_by_id[ident] = api("pokemon-species", ident)
        families.append({"key": name, "base_id": base, "chain_id": int(chain_id), "species": ids, "evolvable": len(ids) > 1})
    mew = api('pokemon-species', 151)
    mew_chain_id = mew['evolution_chain']['url'].strip('/').split('/')[-1]
    mew_chain = flatten(api('evolution-chain', mew_chain_id)['chain'])
    assert len(mew_chain) == 1, 'Recheck Mew evolution data before continuing'
    species_by_id[151] = mew
    pokemon = []
    for ident, species in sorted(species_by_id.items()):
        data = api('pokemon', ident)
        gif_url = f'https://raw.githubusercontent.com/PokeAPI/sprites/{SPRITES_COMMIT}/sprites/pokemon/versions/generation-v/black-white/animated/{ident}.gif'
        gif = download(gif_url, OUT / f'{ident}.gif')
        image = Image.open(io.BytesIO(gif))
        image.convert('RGBA').save(OUT / f'{ident}.png')
        pokemon.append({'id': ident, 'name': species['name'], 'name_zh': localized(species),
                        'types': [row['type']['name'] for row in data['types']],
                        'height_dm': data['height'], 'weight_hg': data['weight'],
                        'sprite': f'assets/pokemon/{ident}.gif', 'sprite_url': gif_url,
                        'sha256': hashlib.sha256(gif).hexdigest()})
        print(f"Fetched #{ident} {localized(species)}", flush=True)
    catalogue = {'schema': 1, 'source': 'PokeAPI', 'sprites_commit': SPRITES_COMMIT,
                 'data_commit': DATA_COMMIT, 'families': families, 'pokemon': pokemon,
                 'non_evolving': [{'id': 151, 'name_zh': localized(mew), 'selectable': False}],
                 'growth': {'levels': 12, 'species_evolution_levels': [5, 9]}}
    (ROOT / 'assets/catalogue.json').write_text(json.dumps(catalogue, ensure_ascii=False, indent=2) + '\n')
    atlas(pokemon)
    print(f"Generated {len(pokemon)} species and {len(families)} evolution families.")


if __name__ == '__main__':
    main()
